---
title: "Litorela"
author: "Pavel Jakubec"
date: "13. února 2016"
output: 
  html_document: 
    keep_md: yes
    theme: journal
---
#Litorela report
```{r}
data=read.csv ("resubmision/prolicovani_ruzne_substraty_2.csv", header=TRUE, sep=";") 

#explore the data
head(data)
str(data)

#put together some model
mod <- glm(cbind(succ, fail) ~ treat, data=data,family=binomial)
mod
summary(mod)
anova(mod, test="Ch")

#see what is going on with residuals
par(mfrow=c(2,2))
plot(mod)
rd=residuals(mod)
plot(rd)
qqnorm(residuals(mod, type="deviance"))
abline(a=0,b=1)
```
```{r}
#back-transformation of coeficients for each treatment to mean survival probability
plogis (mod$coefficients[1]) #intercept (clay)
plogis (mod$coefficients[1]+mod$coefficients[2]) #control
plogis (mod$coefficients[1]+mod$coefficients[3]) #mud
plogis (mod$coefficients[1]+mod$coefficients[4]) #peat
plogis (mod$coefficients[1]+mod$coefficients[5]) #sand
plogis (mod$coefficients[1]+mod$coefficients[6]) #sand_clay
plogis (mod$coefficients[1]+mod$coefficients[7]) #sand_mud
plogis (mod$coefficients[1]+mod$coefficients[8]) #sand_peat
plogis (mod$coefficients[1]+mod$coefficients[9]) #topsoil

```
THE END